# Site settings
title: AngularBits
email: support@larcity.com
description: > # this means to ignore newlines until "baseurl:"
    Little snippets of code that make our developers' lives easier. They might do so for yours too! 
    The awesome AngularJS library from Google is required to utilize these controllers / services / filters.

twitter_username: larcityapps
github_username:  larcitylab

## PRODUCTION CONFIG
url: "http://larcity.com" # the base hostname & protocol for your site
baseurl: "/angularbits" # the subpath of your site, e.g. /blog/

## DEVELOPMENT CONFIG
#url: "http://localhost"
#baseurl: ""
#destination: ./dev-en

destination: "./en"

vars:
    shortname: AngularBits
    company_name: LarCity
    support_email: support@larcity.com
    
# Build settings
markdown: kramdown
timezone: America/New_York
kramdown:
    input: GFM

